### GoodJob CRD resource
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: goodjobs.goodjob.k8s.io
spec:
  group: goodjob.k8s.io
  version: v1alpha1
  names:
    kind: GoodJob
    plural: goodjobs
  scope: Namespaced
---
### Pipeline CRD resource
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.goodjob.k8s.io
spec:
  group: goodjob.k8s.io
  version: v1alpha1
  names:
    kind: Pipeline
    plural: pipelines
  scope: Namespaced
---
### Pipeline CRD resource
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: corntriggers.goodjob.k8s.io
spec:
  group: goodjob.k8s.io
  version: v1alpha1
  names:
    kind: CornTrigger
    plural: corntriggers
  scope: Namespaced
---



###  Good Job 服务需要的相关角色的设定
apiVersion: v1
kind: Namespace
metadata:
   name: good-job
   labels:
     name: good-job
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: good-job
  namespace: good-job
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: good-job-server-role
rules:
- apiGroups: ["goodjob.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["jobs", "cornjobs"]
  verbs: ["create", "get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: good-job-server-role-binding
subjects:
- kind: ServiceAccount
  name: good-job
  namespace: good-job
roleRef:
  kind: ClusterRole
  name: good-job-server-role
  apiGroup: rbac.authorization.k8s.io
---



### Good Job 服务的部署
apiVersion: v1
kind: Service
metadata:
  name: goodjob
  namespace: good-job
spec:
  ports:
  - port: 80
    targetPort: 3333
    protocol: HTTP
    name: http
  selector:
    app: grafana
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goodjob
  namespace: good-job
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goodjob
    spec:
      serviceAccountName: good-job
      containers:
      - name: goodjob
        image: prophet/goodjob:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3333
---

