#apiVersion: apiextensions.k8s.io/v1beta1
#kind: CustomResourceDefinition
#metadata:
#  name: goodjobs.goodjob.k8s.io
#spec:
#  group: goodjob.k8s.io
#  version: v1alpha1
#  names:
#    kind: GoodJob
#    plural: goodjobs
#  scope: Namespaced
#  subresources:
#    status: {}
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#   name: good-job
#   labels:
#     name: good-job
#---
apiVersion: goodjob.k8s.io/v1alpha1
kind: GoodJob
metadata:
  name: test1
  namespace: good-job
spec:
  shard:
    type: config
    shards:
    - "1-3"
    - "4-6"
    - "7-9"
  template:
    metadata:
      name: test
    spec:
      containers:
      - image: busybox
        name: test
        command: ["env"]
      restartPolicy: OnFailure
status:
  status: 1
#--
#apiVersion: batch/v1
#kind: Job
#metadata:
# labels:
#   app: job
#   project: lykops
#   version: v1
# name: test
# namespace: good-job
#spec:
# completions: 50
# parallelism: 5
# template:
#   metadata:
#     labels:
#       app: job
#       job-name: test
#       project: test
#       version: v1
#     name: test
#   spec:
#     containers:
#     - command: ['sleep','60']
#       image: hello
#       name: test
#     restartPolicy: Never
