/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/fudali113/good-job/pkg/apis/goodjob/v1alpha1"
	scheme "github.com/fudali113/good-job/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CornTriggersGetter has a method to return a CornTriggerInterface.
// A group's client should implement this interface.
type CornTriggersGetter interface {
	CornTriggers(namespace string) CornTriggerInterface
}

// CornTriggerInterface has methods to work with CornTrigger resources.
type CornTriggerInterface interface {
	Create(*v1alpha1.CornTrigger) (*v1alpha1.CornTrigger, error)
	Update(*v1alpha1.CornTrigger) (*v1alpha1.CornTrigger, error)
	UpdateStatus(*v1alpha1.CornTrigger) (*v1alpha1.CornTrigger, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CornTrigger, error)
	List(opts v1.ListOptions) (*v1alpha1.CornTriggerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CornTrigger, err error)
	CornTriggerExpansion
}

// cornTriggers implements CornTriggerInterface
type cornTriggers struct {
	client rest.Interface
	ns     string
}

// newCornTriggers returns a CornTriggers
func newCornTriggers(c *GoodjobV1alpha1Client, namespace string) *cornTriggers {
	return &cornTriggers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cornTrigger, and returns the corresponding cornTrigger object, and an error if there is any.
func (c *cornTriggers) Get(name string, options v1.GetOptions) (result *v1alpha1.CornTrigger, err error) {
	result = &v1alpha1.CornTrigger{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("corntriggers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CornTriggers that match those selectors.
func (c *cornTriggers) List(opts v1.ListOptions) (result *v1alpha1.CornTriggerList, err error) {
	result = &v1alpha1.CornTriggerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("corntriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cornTriggers.
func (c *cornTriggers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("corntriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cornTrigger and creates it.  Returns the server's representation of the cornTrigger, and an error, if there is any.
func (c *cornTriggers) Create(cornTrigger *v1alpha1.CornTrigger) (result *v1alpha1.CornTrigger, err error) {
	result = &v1alpha1.CornTrigger{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("corntriggers").
		Body(cornTrigger).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cornTrigger and updates it. Returns the server's representation of the cornTrigger, and an error, if there is any.
func (c *cornTriggers) Update(cornTrigger *v1alpha1.CornTrigger) (result *v1alpha1.CornTrigger, err error) {
	result = &v1alpha1.CornTrigger{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("corntriggers").
		Name(cornTrigger.Name).
		Body(cornTrigger).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cornTriggers) UpdateStatus(cornTrigger *v1alpha1.CornTrigger) (result *v1alpha1.CornTrigger, err error) {
	result = &v1alpha1.CornTrigger{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("corntriggers").
		Name(cornTrigger.Name).
		SubResource("status").
		Body(cornTrigger).
		Do().
		Into(result)
	return
}

// Delete takes name of the cornTrigger and deletes it. Returns an error if one occurs.
func (c *cornTriggers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("corntriggers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cornTriggers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("corntriggers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cornTrigger.
func (c *cornTriggers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CornTrigger, err error) {
	result = &v1alpha1.CornTrigger{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("corntriggers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
