/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/fudali113/good-job/pkg/apis/goodjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGoodJobs implements GoodJobInterface
type FakeGoodJobs struct {
	Fake *FakeGoodjobV1alpha1
	ns   string
}

var goodjobsResource = schema.GroupVersionResource{Group: "goodjob.k8s.io", Version: "v1alpha1", Resource: "goodjobs"}

var goodjobsKind = schema.GroupVersionKind{Group: "goodjob.k8s.io", Version: "v1alpha1", Kind: "GoodJob"}

// Get takes name of the goodJob, and returns the corresponding goodJob object, and an error if there is any.
func (c *FakeGoodJobs) Get(name string, options v1.GetOptions) (result *v1alpha1.GoodJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(goodjobsResource, c.ns, name), &v1alpha1.GoodJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GoodJob), err
}

// List takes label and field selectors, and returns the list of GoodJobs that match those selectors.
func (c *FakeGoodJobs) List(opts v1.ListOptions) (result *v1alpha1.GoodJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(goodjobsResource, goodjobsKind, c.ns, opts), &v1alpha1.GoodJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GoodJobList{ListMeta: obj.(*v1alpha1.GoodJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.GoodJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested goodJobs.
func (c *FakeGoodJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(goodjobsResource, c.ns, opts))

}

// Create takes the representation of a goodJob and creates it.  Returns the server's representation of the goodJob, and an error, if there is any.
func (c *FakeGoodJobs) Create(goodJob *v1alpha1.GoodJob) (result *v1alpha1.GoodJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(goodjobsResource, c.ns, goodJob), &v1alpha1.GoodJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GoodJob), err
}

// Update takes the representation of a goodJob and updates it. Returns the server's representation of the goodJob, and an error, if there is any.
func (c *FakeGoodJobs) Update(goodJob *v1alpha1.GoodJob) (result *v1alpha1.GoodJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(goodjobsResource, c.ns, goodJob), &v1alpha1.GoodJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GoodJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGoodJobs) UpdateStatus(goodJob *v1alpha1.GoodJob) (*v1alpha1.GoodJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(goodjobsResource, "status", c.ns, goodJob), &v1alpha1.GoodJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GoodJob), err
}

// Delete takes name of the goodJob and deletes it. Returns an error if one occurs.
func (c *FakeGoodJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(goodjobsResource, c.ns, name), &v1alpha1.GoodJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGoodJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(goodjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GoodJobList{})
	return err
}

// Patch applies the patch and returns the patched goodJob.
func (c *FakeGoodJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GoodJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(goodjobsResource, c.ns, name, data, subresources...), &v1alpha1.GoodJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GoodJob), err
}
