/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/fudali113/good-job/pkg/apis/goodjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCornTriggers implements CornTriggerInterface
type FakeCornTriggers struct {
	Fake *FakeGoodjobV1alpha1
	ns   string
}

var corntriggersResource = schema.GroupVersionResource{Group: "goodjob.k8s.io", Version: "v1alpha1", Resource: "corntriggers"}

var corntriggersKind = schema.GroupVersionKind{Group: "goodjob.k8s.io", Version: "v1alpha1", Kind: "CornTrigger"}

// Get takes name of the cornTrigger, and returns the corresponding cornTrigger object, and an error if there is any.
func (c *FakeCornTriggers) Get(name string, options v1.GetOptions) (result *v1alpha1.CornTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(corntriggersResource, c.ns, name), &v1alpha1.CornTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CornTrigger), err
}

// List takes label and field selectors, and returns the list of CornTriggers that match those selectors.
func (c *FakeCornTriggers) List(opts v1.ListOptions) (result *v1alpha1.CornTriggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(corntriggersResource, corntriggersKind, c.ns, opts), &v1alpha1.CornTriggerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CornTriggerList{ListMeta: obj.(*v1alpha1.CornTriggerList).ListMeta}
	for _, item := range obj.(*v1alpha1.CornTriggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cornTriggers.
func (c *FakeCornTriggers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(corntriggersResource, c.ns, opts))

}

// Create takes the representation of a cornTrigger and creates it.  Returns the server's representation of the cornTrigger, and an error, if there is any.
func (c *FakeCornTriggers) Create(cornTrigger *v1alpha1.CornTrigger) (result *v1alpha1.CornTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(corntriggersResource, c.ns, cornTrigger), &v1alpha1.CornTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CornTrigger), err
}

// Update takes the representation of a cornTrigger and updates it. Returns the server's representation of the cornTrigger, and an error, if there is any.
func (c *FakeCornTriggers) Update(cornTrigger *v1alpha1.CornTrigger) (result *v1alpha1.CornTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(corntriggersResource, c.ns, cornTrigger), &v1alpha1.CornTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CornTrigger), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCornTriggers) UpdateStatus(cornTrigger *v1alpha1.CornTrigger) (*v1alpha1.CornTrigger, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(corntriggersResource, "status", c.ns, cornTrigger), &v1alpha1.CornTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CornTrigger), err
}

// Delete takes name of the cornTrigger and deletes it. Returns an error if one occurs.
func (c *FakeCornTriggers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(corntriggersResource, c.ns, name), &v1alpha1.CornTrigger{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCornTriggers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(corntriggersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CornTriggerList{})
	return err
}

// Patch applies the patch and returns the patched cornTrigger.
func (c *FakeCornTriggers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CornTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(corntriggersResource, c.ns, name, data, subresources...), &v1alpha1.CornTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CornTrigger), err
}
