/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	goodjobv1alpha1 "github.com/fudali113/good-job/pkg/apis/goodjob/v1alpha1"
	versioned "github.com/fudali113/good-job/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fudali113/good-job/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/fudali113/good-job/pkg/client/listers/goodjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CornTriggerInformer provides access to a shared informer and lister for
// CornTriggers.
type CornTriggerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CornTriggerLister
}

type cornTriggerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCornTriggerInformer constructs a new informer for CornTrigger type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCornTriggerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCornTriggerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCornTriggerInformer constructs a new informer for CornTrigger type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCornTriggerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GoodjobV1alpha1().CornTriggers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GoodjobV1alpha1().CornTriggers(namespace).Watch(options)
			},
		},
		&goodjobv1alpha1.CornTrigger{},
		resyncPeriod,
		indexers,
	)
}

func (f *cornTriggerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCornTriggerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cornTriggerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&goodjobv1alpha1.CornTrigger{}, f.defaultInformer)
}

func (f *cornTriggerInformer) Lister() v1alpha1.CornTriggerLister {
	return v1alpha1.NewCornTriggerLister(f.Informer().GetIndexer())
}
