/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	goodjobv1alpha1 "github.com/fudali113/good-job/pkg/apis/goodjob/v1alpha1"
	versioned "github.com/fudali113/good-job/pkg/client/clientset/versioned"
	internalinterfaces "github.com/fudali113/good-job/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/fudali113/good-job/pkg/client/listers/goodjob/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GoodJobInformer provides access to a shared informer and lister for
// GoodJobs.
type GoodJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GoodJobLister
}

type goodJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGoodJobInformer constructs a new informer for GoodJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGoodJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGoodJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGoodJobInformer constructs a new informer for GoodJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGoodJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GoodjobV1alpha1().GoodJobs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GoodjobV1alpha1().GoodJobs(namespace).Watch(options)
			},
		},
		&goodjobv1alpha1.GoodJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *goodJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGoodJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *goodJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&goodjobv1alpha1.GoodJob{}, f.defaultInformer)
}

func (f *goodJobInformer) Lister() v1alpha1.GoodJobLister {
	return v1alpha1.NewGoodJobLister(f.Informer().GetIndexer())
}
